#!/bin/bash

domain=demo.example.com

# Generate cert
openssl req \
    -x509 \
    -nodes \
    -newkey rsa:4096 \
    -keyout key_temp.pem \
    -subj "/C=US/ST=CA/L=San Francisco/O=Token Inc/CN=${domain}" \
    -out cert.pem \
    -days 120

# Convert RSA key into pkcs8 format to consume from java
openssl pkcs8 \
    -topk8 \
    -inform PEM \
    -outform PEM \
    -nocrypt \
    -in key_temp.pem \
    -out key.pem

rm key_temp.pem
