#!/bin/bash

# ./regenerate-certs : Generate key.pem and cert.pem for TLS communication

# ./regenerate-certs 8.8.8.8 : As above, but set up to serve
#                                        from a certain ip address instead
#                                        of default ip.

ip=8.8.8.8 # default ip

if [ "$1" != "" ]; then
    ip=$1
fi

# Generate cert
openssl req \
    -x509 \
    -nodes \
    -newkey rsa:4096 \
    -keyout key_temp.pem \
    -subj "/C=US/ST=CA/L=San Francisco/O=Token Inc/CN=${ip}" \
    -reqexts SAN \
    -extensions SAN \
    -config <(cat /etc/ssl/openssl.cnf \
            <(printf "\n[SAN]\nsubjectAltName=IP:${ip}")) \
    -out cert.pem \
    -days 120

# Convert RSA key into pkcs8 format to consume from java
openssl pkcs8 \
    -topk8 \
    -inform PEM \
    -outform PEM \
    -nocrypt \
    -in key_temp.pem \
    -out key.pem

rm key_temp.pem
